name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for actions/deploy-pages
      pages: write # Needed for actions/deploy-pages
      id-token: write # Needed for actions/deploy-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./src/client/
        
      - name: Build site
        run: npm run build
        working-directory: ./src/client/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/client/dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
